# Generated by Django 4.2.13 on 2024-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_blogpost_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_friendly',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
