# Generated by Django 4.2.13 on 2024-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_project_url_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url_friendly',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
