name: build

on:
  push:
    brances:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3

      -
        name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/personalsite:latest

  republish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger 
        uses: satak/webrequest-action@master
        with:
          url: 81.99.37.97:8080/v1/update
          method: POST
          payload: ''
          headers: '{"Authentication": "Bearer ${{ env.TOKEN }}"}'